### ISSUE TITLE
(Question) How to obtain the following text?

### ISSUE THREAD

**Issue by zenflow** [kevgo/node-text-stream-search#22]
What is the suggested way to read the text that follows the search text?

I.e. how can I obtain `name` from this: `await streamSearch.waitForText('Name: ')`

**Comment by LinusU** [comment]
I don't think it's currently possible, but it would be cool if it could work something like this:

```js
const name = (await streamSearch.waitForRegex(/Name: (.*)$/))[1]
```

**Comment by kevgo** [comment]
Hey @zenflow and @LinusU, sorry for the delayed reply, I just discovered this ticket due to a missing subscription to this project. I have implemented @LinusU's suggestion. Now you can do this:

```js
const matching = await streamSearch.waitForRegex("listening at port \\d+")
// matching contains something like "listening at port 3000"
```

Since this is kind of breaking the API, I have released version 3.0.0 that implements this. Hope you find this helpful!

**Comment by zenflow** [comment]
@kevgo This is great! But without code examples this feature will be difficult to discover.

**Comment by kevgo** [comment]
Hey @zenflow, this is now documented in the [Readme](https://github.com/kevgo/node-text-stream-search/blob/master/README.md) for this project. Is that sufficiently documented?
